### ISSUE TITLE
results on llama

### ISSUE THREAD

**Issue by liuxingpeng520521** [trishullab/copra#23]
How are your results on llama, my attempts here have been rather poor.

**Comment by amit9oct** [comment]
Code Llama gives 0% on miniF2F for one-shot, however, COPRA can enhance the Llama performance to 5.73% (when used with [LiteLLM](https://github.com/BerriAI/litellm) style chat format for GPT-4 requests). The performance is lower on the native [Llama 2 chat format](https://gpus.llm-utils.org/llama-2-prompt-template/), this is because raw LLama 2 doesn't have an equivalent of example conversation like GPT-4. Llama 2 chat format only supports `content` and `role`, unlike `content`, `role`, and `name` in OpenAI format. I'm working on changes to make it work better with the native LLama 2 chat format.

You can check the logs from the Copra run on CodeLlama with 5.73% improvement [here](https://github.com/trishullab/copra/blob/main/docs/static/selected_results/copra-code-llama.log). In the logs search for `SearchResult: [SUCCESS]` keywords to find the Code Llama results.

**Comment by liuxingpeng520521** [comment]
Can you show me a demo?

**Comment by amit9oct** [comment]
How to run COPRA with Code Llama?

The instructions for running COPRA with Llama are the same as in [README](https://github.com/trishullab/copra/tree/main#readme). 
Then you need to run the following command from the root of the repo:
`python src/main/eval_benchmark.py prompt_settings=lean_dfs env_settings=bm25_retrieval eval_settings=n_500_dfs_codellama_always_retrieve_no_ex benchmark=miniF2F`.

Note that the latest implementation doesn't use `LiteLLM` so you will not get a good performance. We want to move away from `LiteLLM` chat format and only use `Llama 2` chat format in the future. 
However, you can switch to `LiteLLM` based chat format by reverting the code changes in the following files:
```
1. https://github.com/trishullab/copra/blob/6608f7fd45980f06d4b5b2fe9d4dbc7d2aa51211/src/gpts/llama_access.py
2. https://github.com/trishullab/copra/blob/6608f7fd45980f06d4b5b2fe9d4dbc7d2aa51211/src/gpts/start_llama.sh
```

In case you don't want to revert to `LiteLLM`. You can check the logs from the COPRA run on CodeLlama using `LiteLLM` which led to the gain of 5.73% [here](https://github.com/trishullab/copra/blob/main/docs/static/selected_results/copra-code-llama.log). This has the prompts for intermediate steps too.
