### ISSUE TITLE
tree-of-thought style approach

### ISSUE THREAD

**Issue by aa755** [trishullab/copra#55]
have you tried a tree-of-thought style approach where the LLM is asked to come up multiple possible next steps and to critique each of those steps (and the broader proof strategy behind those steps) before picking the best choice?

**Comment by aa755** [comment]
From the algorithm in the COPRA paper, it looks like if the LLM picks a wrong action that typechecks and does not make the goal more difficult in a detectable way, there is no way to backtrack and it is game over. For example, it could chose a wrong value of an existential, or decide to prove the wrong side of a disjunction. Do you see such failure modes in the lemmas COPRA could not prove?

![image](https://github.com/trishullab/copra/assets/499314/26b4d4b4-246e-49c5-a71f-da6c8c072bc3)

**Comment by amit9oct** [comment]
Hi,
Here is the answer to your questions:
1. We have not tried the tree of thought approach as you have mentioned.
2. It can backtrack if there is an eventual failure (let's say arising because of picking up a wrong existential). For most cases, what we observed is picking up a wrong choice will either lead to path where proof can no longer make any progress (same state) or failure to find any new tactic which can make it progress (change of state). In that scenario the backtracking can happen. However, practically it is quite possible that this detection happens too late and then we don't have enough remaining query budget to backtrack.

**Comment by aa755** [comment]
thanks for the answers.

**Comment by aa755** [comment]
From the paper, some details about the backtracking approach are not clear to me. Below is my guess of how COPRA does it. Can you please confirm or correct it?

lets say COPRA is at the goal O and which it arrived after taking the action A on goal O'. if after trying a few times all the actions that the LLM comes up with are invalid (error or results in a more complex/difficult goal), COPRA adds A to BAD(O') and then invokes COPRA(O')

**Comment by amit9oct** [comment]
Yes you are right. To be precise COPRA tries until LLM keeps generating some different tactic than those which we already know failed for that state. Once LLM repeats one of the tactic which failed previously we backtrack.
